openapi: '3.0.2'
info:
  title: Specification open api 
  version: '1.0'
servers:
  - url: https://api.server.test/v1
tags:
  - Books
  - Author
paths:
  /book:
    get:
      tags:
        - Books  
      summary: get all books
      operationId: getBooks
      parameters:
      - in: query
        name: bookname
        description: filter a bookName order by realise date 
        schema:
          type: array
        required: false
      - in: query
        name: releaseDateMin
        description: |
            If  `releaseDateMax` is not provided, `releaseDateMin` is ignored.
            `releaseDateMin` can not be after `releaseDateMax`.
        schema:
          type: string
          format: date
        required: false  
      - in: query
        name: releaseDateMax
        description: |
            If  `releaseDateMin` is not provided, `releaseDateMax` is ignored.
            `releaseDateMax` can not be after `releaseDateMin`.
        schema:
          type: string
          format: date
        required: false 
      - $ref: '#/components/parameters/QueryPagination'       
      responses:
       200:
        $ref: "#/components/responses/Response200"
        description: the list of bookname order by release date given 
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Book'
    put:
      tags:
        - Books
      summary: Create or update a books 
      operationId: crupdateBook
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Book'
      responses:
        200:
          description: the list of created or updated books 
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Book'
  /books/{bookId}/authors/{authorId}:
    put:
      tags: 
        - Books
      operationId: addAuthorIntoBoook
      parameters:
       - in: path
         name: bookId
         schema:
          type: string
         required: true
       - in: path
         name: authorId
         schema:
          type: string
         required: true
      responses:
        200:
          description: The list of created or updated books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
  /books/authors:
    put:
      tags:
        - Books
      summary: associate multiple books to an author
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/UpdateBookAuthor"  

      responses:
        200:
          description: A book has been associate to an author
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: "#/components/schemas/Book"
  /books/import:
    post:
      tags:
        - Book
      summary: Import books from Excel or JSON
      operationId: importBooks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/ImportBook'
          application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:  
            schema:
              type: object
              properties:
                excel:  
                  type: string 
        description: Excel or JSON file for book import
  /author:
    get:
      tags:
        - Author
      summary: get all author
      operationId: getAuthor
      parameters:
        - in: query
          name: authorName
          description: filter a author by authorName
          schema: 
            type: string
          required: false
        - $ref: "#/components/parameters/QueryPagination"
      responses:
        200:
         description: the list of author
         content:
           application/json:
            schema: 
              type: array
              items:
                $ref: "#/components/schemas/Author"
    put:
      tags:
        - Author
      summary: create or update author
      operationId: crupdateAuthor
      requestBody:
       content:
         application/json:
          schema: 
            type: array
            items:
              $ref: "#/components/schemas/Author"
      responses:
        200:
          description: the list of craeted or updated author
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Author"
  /author/import:
    post : 
      tags:
        - Author
      summary: Import author for excel or JSON 
      operationId: ImportAuthor
      requestBody:
        content:
          application/json:
            schema: 
              oneOf:
                - $ref: '#/components/schemas/ImportAuthor'
          application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
            schema:
             type: object
             properties:
              excel:
                  type: string
        description: excel or JSON file for author Import

  /authors/{aId}:
    delete:
      tags:
        - Author
      summary: delete an  author
      operationId: deleteAuthor
      parameters:
        - in: path
          name: authorId
          description: author identifier to be deleted
          schema: 
            type: array
          required: true
      responses:
        200:
          description: the author deleted 
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: "#/components/schemas/Author"

  /visitors:
    get:
      summary: Get all visitors
      operationId: getAllVisitors
      responses:
        200:
          description: List of visitors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Visitor'
    post:
      summary: Create a new visitor
      operationId: createVisitor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Visitor'
      responses:
        201:
          description: Visitor created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Visitor'
  /books/borrowed:
    get:
      summary: Get a list of borrowed books
      operationId: getBorrowedBooks
      responses:
        200:
          description: List of borrowed books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'

  /books/available:
    get:
      summary: Get a list of available books
      operationId: getAvailableBooks
      responses:
        200:
          description: List of available books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'

  /visitors/{visitorId}/activities:
    get:
      summary: Get visitor activities for a specified period
      operationId: getVisitorActivities
      parameters:
        - in: path
          name: visitorId
          schema:
            type: string
          required: true
        - in: query
          name: startDate
          schema:
            type: string
            format: date-time
          description: Start date for the period
          required: true
        - in: query
          name: endDate
          schema:
            type: string
            format: date-time
          description: End date for the period
          required: true
      responses:
        200:
          description: Visitor activities for the specified period
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Borrowing'


components:
  schemas:
    Book:
      type: object
      properties:
        id:
         type: string
        bookname:
         type: string
        author:
         $ref: "#/components/schemas/Author"
        pageNumber:
         type: integer
        topic:
         type: string
         enum:
           - ROMANCE
           - COMEDY
           - OTHER
        isBorrowed:
          type: boolean
    Author: 
      type: object
      properties:
        id: 
          type: string
        authorName:
          type: string
        sex:
          $ref: "#/components/schemas/Sex"
    Sex: 
      type: string
      enum:
        - M
        - F 
    CrupdateBook:
      type: object
      properties:
        id:
          type: string
        bookName:
          type: string
        pageNumbers:
          type: integer
        topic:
          type: string
          enum:
            - ROMANCE
            - COMEDY
            - OTHER
        releaseDate:
          type: string
          format: date 
    UpdateBookAuthor:
      type: object
      properties:
        bookId: 
           type: string
        authorId:
           type: string
      required:
        - bookId
        - authorId
    ImportAuthor:
      anyOf:
        - type: object
          properties:
            items:
              $ref: "#/components/schemas/Author"
        - type: object
          properties:
            excel:
              type: string
    ImportBook:
      anyOf:
        - type: object
          properties:
            items:
              $ref: "#/components/schemas/Book"
        - type: object
          properties:
            excel:
              type: string
    Visitor:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        reference:
          type: string
      required:
          - id
          - name
          - reference
    Borrowing:
      type: object
      properties:
        bookId:
          type: string
        visitorId:
          type: string
        borrowedDate:
          type: string
          format: date-time
        returnedDate:
          type: string
          format: date-time

  parameters:
    QueryPagination:
      name: queryPagination 
      in: query
      schema: 
        type: object
        properties:
          Page:
           type: integer
           default: 1
          pageSize:
            type: integer
            default: 30
  responses:
    BaseResponse : 
      description: response structure 
      content:
        application/json:
          schema:   
            type: object
            properties:
              status:
                type: object
              codeOfStatus:
                type: integer
              messages:
                type: string
              body: 
                type: string
    Response200:
      description: code of status 200 response successfully
      content:
        application/json:
          schema: 
            allOf:
              - $ref: '#/components/responses/BaseResponse'
              - type: object
                properties:
                  status: 
                    properties:
                      codeOfStatus:
                        type: integer
                        enum:
                          - 200
                      messages:
                        type: string
                  body:
                    type: object
                    properties:
                      data: 
                        type: array
                        items:
                          $ref: "#/components/schemas/Book" 
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic








   
